# A1 — OLS Cross-Section

**Famiglia A** | Una riga per contatore | Baseline della tesi

```
pct_silente_i = β₀ + β·X_i + ε_i
```
- Variabile dipendente: proporzione di finestre silenti [0, 1]
- Include variabili statiche + aggregate dinamiche
- **Prerequisito**: eseguire `00_preparazione_dati/01_Preparazione_dati_v2.ipynb` per generare i parquet

In [1]:
# ══════════════════════════════════════════════════════════════════════════════
# CELLA 1 — Setup: mount Drive + clone repo + caricamento parquet
# ══════════════════════════════════════════════════════════════════════════════

from google.colab import drive
drive.mount("/content/drive")

import subprocess, os, sys

REPO_URL  = "https://github.com/swaggincoffee-bit/Tesi.git"
REPO_PATH = "/content/Tesi"
if not os.path.exists(REPO_PATH):
    subprocess.run(["git", "clone", REPO_URL, REPO_PATH], check=True)
else:
    subprocess.run(["git", "-C", REPO_PATH, "pull"], check=True)
sys.path.insert(0, REPO_PATH)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import warnings
warnings.filterwarnings("ignore")

from src.config import (
    COL_DATA_INST, COL_ANNO_COSTR, COL_CONSUMO,
    COL_MODELLO, COL_TECN_COM, COL_COSTRUTTORE,
    FNAME_CS,
)

PROC = "/content/drive/MyDrive/Contatori/OUTPUT/"
OUT  = "/content/drive/MyDrive/Contatori/OUTPUT/"

df_cs = pd.read_parquet(PROC + FNAME_CS)

print(f"df_cs caricato: {df_cs.shape}")
display(df_cs.head(3))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
df_cs caricato: (226702, 53)

,04IND - Provincia (cod),04IND - Comune (cod),04IND - CAP (cod),03IMPS - STec - Accessibile (cod),03IMPS - PDR/POD - Esterno (cod),03IMPS - Stato telegestione (cod),03IMPS - Operandi - Cons.Anno PDR (desc),11MDEF - Installazione(dta),11MDEF - Costruttore (cod),11MDEF - Anno Costruzione (cod),...,gg_da_installazione,firmware_num,gg_da_ult_com,gg_da_ult_mis,costruttore,modello,tecnologia,comune,accessibile,telegestione
0,Reggio nell'Emilia,Albinea,42020,ACCESSIBILE,15441000000750,GT,916,17.12.2024,METERSIT,2024,...,370,732,-40.0,-39.0,METERSIT,G4_NBIOT,NBIOT,Albinea,ACCESSIBILE,GT
1,Reggio nell'Emilia,Albinea,42020,ACCESSIBILE,15441000001565,GT,2182,22.10.2024,METERSIT,2024,...,426,732,-44.0,-43.0,METERSIT,G6_NBIOT,NBIOT,Albinea,ACCESSIBILE,GT
2,Reggio nell'Emilia,Albinea,42020,ACCESSIBILE,15441000002472,GT,156,11.08.2017,METERSIT,2017,...,3055,400,-45.0,-43.0,METERSIT,DOMUS NEXT G4,GPRS,Albinea,ACCESSIBILE,GT

In [2]:
# CELLA 2 - Feature engineering

from sklearn.preprocessing import LabelEncoder

df_lett_re = pd.read_parquet(PROC + "df_lett_re.parquet")
ref_date = pd.to_datetime(df_lett_re["data_lettura"]).max()
del df_lett_re

# Categoriche -> encoded
for short, col in {"costruttore_enc":  "costruttore",
                   "modello_enc":      "modello",
                   "tecnologia_enc":   "tecnologia",
                   "comune_enc":       "comune",
                   "accessibile_enc":  "accessibile",
                   "telegestione_enc": "telegestione"}.items():
    df_cs[short] = LabelEncoder().fit_transform(df_cs[col].fillna("N/A"))

FEATURES = [
    "anni_da_costruzione",
    "consumo_annuo",
    "gg_da_installazione",
    "firmware_num",
    "gg_da_ult_com",
    "gg_da_ult_mis",
    "costruttore_enc",
    "modello_enc",
    "tecnologia_enc",
    "comune_enc",
    "accessibile_enc",
    "telegestione_enc",
    "pct_err",
    *[f"diag_bit_{i:02d}" for i in range(16)],
]
TARGET = "pct_silente"

df_model = df_cs[FEATURES + [TARGET]].dropna()
print(f"Osservazioni: {len(df_model):,}  (NaN scartati: {len(df_cs)-len(df_model):,})")
display(df_model[FEATURES].describe().round(2))

Osservazioni: 219,330  (NaN scartati: 7,372)

,anni_da_costruzione,consumo_annuo,gg_da_installazione,firmware_num,gg_da_ult_com,gg_da_ult_mis,costruttore_enc,modello_enc,tecnologia_enc,comune_enc,...,diag_bit_06,diag_bit_07,diag_bit_08,diag_bit_09,diag_bit_10,diag_bit_11,diag_bit_12,diag_bit_13,diag_bit_14,diag_bit_15
count,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00,...,219330.00,219330.00,219330.0,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00,219330.00
mean,5.65,845.58,2146.47,503.58,-23.62,-22.60,4.49,6.74,2.35,22.43,...,0.00,0.00,0.0,0.00,0.01,0.00,0.00,0.03,0.03,0.01
std,2.77,876.57,1005.79,1075.01,75.43,76.69,1.47,4.02,1.17,9.38,...,0.01,0.02,0.0,0.01,0.09,0.03,0.03,0.18,0.16,0.12
min,0.00,0.00,-9.00,138.00,-45.00,-44.00,1.00,0.00,0.00,0.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,4.00,278.00,1417.00,500.00,-45.00,-43.00,4.00,6.00,2.00,16.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,7.00,708.00,2510.00,500.00,-44.00,-43.00,4.00,6.00,3.00,27.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,8.00,1193.00,2884.00,503.00,-43.00,-42.00,4.00,11.00,3.00,27.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,24.00,51000.00,3975.00,250801.00,2031.00,688.00,7.00,15.00,3.00,41.00,...,1.00,1.00,1.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [3]:
print(df_cs.columns.tolist())

['04IND - Provincia (cod)', '04IND - Comune (cod)', '04IND - CAP (cod)', '03IMPS - STec - Accessibile (cod)', '03IMPS - PDR/POD - Esterno (cod)', '03IMPS - Stato telegestione (cod)', '03IMPS - Operandi - Cons.Anno PDR (desc)', '11MDEF - Installazione(dta)', '11MDEF - Costruttore (cod)', '11MDEF - Anno Costruzione (cod)', '11MDEF - Materiale (cod)', '11MDEF - Numero Serie (cod)', 'MEAS - PDR (conteggio)', '_key', 'MATRICOLA CONTATORE', 'PDR', 'MODELLO CONTATORE', 'VERSIONE FIRMWARE', 'Tecnologia di comunicazione', 'Data ultima comunicazione', 'Data ultima misura', 'pct_silente', 'n_finestre', 'silente_prevalente', 'pct_err', 'diag_bit_00', 'diag_bit_01', 'diag_bit_02', 'diag_bit_03', 'diag_bit_04', 'diag_bit_05', 'diag_bit_06', 'diag_bit_07', 'diag_bit_08', 'diag_bit_09', 'diag_bit_10', 'diag_bit_11', 'diag_bit_12', 'diag_bit_13', 'diag_bit_14', 'diag_bit_15', 'anni_da_costruzione', 'consumo_annuo', 'gg_da_installazione', 'firmware_num', 'gg_da_ult_com', 'gg_da_ult_mis', 'costruttore', 'modello', 'tecnologia', 'comune', 'accessibile', 'telegestione', 'costruttore_enc', 'modello_enc', 'tecnologia_enc', 'comune_enc', 'accessibile_enc', 'telegestione_enc']

In [4]:
# ══════════════════════════════════════════════════════════════════════════════
# CELLA 3 — OLS con statsmodels
# ══════════════════════════════════════════════════════════════════════════════

X = sm.add_constant(df_model[FEATURES])
y = df_model[TARGET]

model = sm.OLS(y, X).fit(cov_type="HC3")  # errori robusti eteroschedasticità
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            pct_silente   R-squared:                       0.388
Model:                            OLS   Adj. R-squared:                  0.388
Method:                 Least Squares   F-statistic:                     6936.
Date:                Sun, 10 May 2026   Prob (F-statistic):               0.00
Time:                        22:26:12   Log-Likelihood:             2.2941e+05
No. Observations:              219330   AIC:                        -4.588e+05
Df Residuals:                  219300   BIC:                        -4.584e+05
Df Model:                          29
Covariance Type:                  HC3
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                   0.9201      0.003    336.957      0.000       0.915       0.925
anni_da_costruzione    -0.0020      0.000     -5.002      0.000      -0.003      -0.001
consumo_annuo        2.758e-07   2.04e-07      1.355      0.175   -1.23e-07    6.75e-07
gg_da_installazione  4.472e-06   1.08e-06      4.133      0.000    2.35e-06    6.59e-06
firmware_num          1.06e-06    5.7e-07      1.860      0.063    -5.7e-08    2.18e-06
gg_da_ult_com        1.892e-05   5.57e-06      3.395      0.001       8e-06    2.98e-05
gg_da_ult_mis           0.0003   5.45e-06     46.697      0.000       0.000       0.000
costruttore_enc         0.0002      0.000      1.273      0.203   -9.04e-05       0.000
modello_enc             0.0047   6.38e-05     73.445      0.000       0.005       0.005
tecnologia_enc          0.0014      0.000      6.415      0.000       0.001       0.002
comune_enc             -0.0002   2.08e-05    -11.144      0.000      -0.000      -0.000
accessibile_enc        -0.0019      0.000     -6.006      0.000      -0.002      -0.001
telegestione_enc       -0.0403      0.003    -15.050      0.000      -0.045      -0.035
pct_err                -0.1562      0.001   -236.049      0.000      -0.157      -0.155
diag_bit_00             0.0896      0.311      0.288      0.773      -0.519       0.698
diag_bit_01             0.2813      0.311      0.906      0.365      -0.327       0.890
diag_bit_02            -0.2297      0.001   -193.280      0.000      -0.232      -0.227
diag_bit_03            -0.0593      0.002    -37.086      0.000      -0.062      -0.056
diag_bit_04            -0.0300      0.001    -38.638      0.000      -0.032      -0.028
diag_bit_05            -0.0351      0.002    -20.091      0.000      -0.039      -0.032
diag_bit_06             0.0110      0.018      0.618      0.537      -0.024       0.046
diag_bit_07            -0.0360      0.017     -2.161      0.031      -0.069      -0.003
diag_bit_08            -0.0008      0.024     -0.034      0.973      -0.049       0.047
diag_bit_09            -0.0462      0.028     -1.663      0.096      -0.101       0.008
diag_bit_10            -0.0289      0.002    -15.713      0.000      -0.032      -0.025
diag_bit_11            -0.0181      0.005     -3.681      0.000      -0.028      -0.008
diag_bit_12            -0.0271      0.008     -3.524      0.000      -0.042      -0.012
diag_bit_13            -0.0337      0.002    -15.847      0.000      -0.038      -0.030
diag_bit_14            -0.0105      0.002     -4.466      0.000      -0.015      -0.006
diag_bit_15            -0.0299      0.001    -22.587      0.000      -0.032      -0.027
==============================================================================
Omnibus:                     9991.143   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11361.535
Skew:                          -0.554   Prob(JB):                         0.00
Kurtosis:                       2.872   Cond. No.                     1.20e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.2e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [5]:
# ══════════════════════════════════════════════════════════════════════════════
# CELLA 3 — OLS con statsmodels
# ══════════════════════════════════════════════════════════════════════════════

X = sm.add_constant(df_model[FEATURES])
y = df_model[TARGET]

model = sm.OLS(y, X).fit(cov_type="HC3")  # errori robusti eteroschedasticità
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            pct_silente   R-squared:                       0.388
Model:                            OLS   Adj. R-squared:                  0.388
Method:                 Least Squares   F-statistic:                     6936.
Date:                Sun, 10 May 2026   Prob (F-statistic):               0.00
Time:                        22:26:14   Log-Likelihood:             2.2941e+05
No. Observations:              219330   AIC:                        -4.588e+05
Df Residuals:                  219300   BIC:                        -4.584e+05
Df Model:                          29
Covariance Type:                  HC3
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                   0.9201      0.003    336.957      0.000       0.915       0.925
anni_da_costruzione    -0.0020      0.000     -5.002      0.000      -0.003      -0.001
consumo_annuo        2.758e-07   2.04e-07      1.355      0.175   -1.23e-07    6.75e-07
gg_da_installazione  4.472e-06   1.08e-06      4.133      0.000    2.35e-06    6.59e-06
firmware_num          1.06e-06    5.7e-07      1.860      0.063    -5.7e-08    2.18e-06
gg_da_ult_com        1.892e-05   5.57e-06      3.395      0.001       8e-06    2.98e-05
gg_da_ult_mis           0.0003   5.45e-06     46.697      0.000       0.000       0.000
costruttore_enc         0.0002      0.000      1.273      0.203   -9.04e-05       0.000
modello_enc             0.0047   6.38e-05     73.445      0.000       0.005       0.005
tecnologia_enc          0.0014      0.000      6.415      0.000       0.001       0.002
comune_enc             -0.0002   2.08e-05    -11.144      0.000      -0.000      -0.000
accessibile_enc        -0.0019      0.000     -6.006      0.000      -0.002      -0.001
telegestione_enc       -0.0403      0.003    -15.050      0.000      -0.045      -0.035
pct_err                -0.1562      0.001   -236.049      0.000      -0.157      -0.155
diag_bit_00             0.0896      0.311      0.288      0.773      -0.519       0.698
diag_bit_01             0.2813      0.311      0.906      0.365      -0.327       0.890
diag_bit_02            -0.2297      0.001   -193.280      0.000      -0.232      -0.227
diag_bit_03            -0.0593      0.002    -37.086      0.000      -0.062      -0.056
diag_bit_04            -0.0300      0.001    -38.638      0.000      -0.032      -0.028
diag_bit_05            -0.0351      0.002    -20.091      0.000      -0.039      -0.032
diag_bit_06             0.0110      0.018      0.618      0.537      -0.024       0.046
diag_bit_07            -0.0360      0.017     -2.161      0.031      -0.069      -0.003
diag_bit_08            -0.0008      0.024     -0.034      0.973      -0.049       0.047
diag_bit_09            -0.0462      0.028     -1.663      0.096      -0.101       0.008
diag_bit_10            -0.0289      0.002    -15.713      0.000      -0.032      -0.025
diag_bit_11            -0.0181      0.005     -3.681      0.000      -0.028      -0.008
diag_bit_12            -0.0271      0.008     -3.524      0.000      -0.042      -0.012
diag_bit_13            -0.0337      0.002    -15.847      0.000      -0.038      -0.030
diag_bit_14            -0.0105      0.002     -4.466      0.000      -0.015      -0.006
diag_bit_15            -0.0299      0.001    -22.587      0.000      -0.032      -0.027
==============================================================================
Omnibus:                     9991.143   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11361.535
Skew:                          -0.554   Prob(JB):                         0.00
Kurtosis:                       2.872   Cond. No.                     1.20e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 1.2e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [6]:
# ══════════════════════════════════════════════════════════════════════════════
# CELLA 5 — Salvataggio risultati
# ══════════════════════════════════════════════════════════════════════════════

risultati = model.summary2().tables[1].reset_index()
risultati.columns = ["variabile", "coef", "std_err", "t", "p_value", "ci_low", "ci_high"]
risultati.to_csv(OUT + "A1_coefficienti_OLS.csv", index=False)

print("✅ Salvati:")
print("  A1_diagnostica_residui.png")
print("  A1_coefficienti_OLS.csv")
display(risultati)

✅ Salvati:
  A1_diagnostica_residui.png
  A1_coefficienti_OLS.csv

,variabile,coef,std_err,t,p_value,ci_low,ci_high
0,const,9.201291e-01,2.730705e-03,336.956554,0.000000e+00,9.147770e-01,9.254812e-01
1,anni_da_costruzione,-1.961296e-03,3.921133e-04,-5.001861,5.677959e-07,-2.729824e-03,-1.192768e-03
2,consumo_annuo,2.758083e-07,2.035463e-07,1.355015,1.754127e-01,-1.231350e-07,6.747516e-07
3,gg_da_installazione,4.472421e-06,1.082174e-06,4.132811,3.583538e-05,2.351399e-06,6.593444e-06
4,firmware_num,1.059749e-06,5.697811e-07,1.859923,6.289638e-02,-5.700128e-08,2.176500e-06
5,gg_da_ult_com,1.892060e-05,5.572431e-06,3.395395,6.852960e-04,7.998841e-06,2.984237e-05
6,gg_da_ult_mis,2.543134e-04,5.446088e-06,46.696529,0.000000e+00,2.436393e-04,2.649875e-04
7,costruttore_enc,1.672633e-04,1.314410e-04,1.272535,2.031832e-01,-9.035642e-05,4.248829e-04
8,modello_enc,4.685468e-03,6.379531e-05,73.445338,0.000000e+00,4.560432e-03,4.810505e-03
9,tecnologia_enc,1.378359e-03,2.148729e-04,6.414767,1.410385e-10,9.572163e-04,1.799503e-03
10,comune_enc,-2.313280e-04,2.075759e-05,-11.144261,7.637547e-29,-2.720122e-04,-1.906439e-04
11,accessibile_enc,-1.850492e-03,3.081157e-04,-6.005835,1.903500e-09,-2.454388e-03,-1.246596e-03
12,telegestione_enc,-4.025631e-02,2.674907e-03,-15.049613,3.472575e-51,-4.549903e-02,-3.501359e-02
13,pct_err,-1.561566e-01,6.615427e-04,-236.049217,0.000000e+00,-1.574532e-01,-1.548600e-01
14,diag_bit_00,8.957071e-02,3.105412e-01,0.288434,7.730144e-01,-5.190788e-01,6.982202e-01
15,diag_bit_01,2.812771e-01,3.105456e-01,0.905751,3.650675e-01,-3.273811e-01,8.899352e-01
16,diag_bit_02,-2.296895e-01,1.188379e-03,-193.279693,0.000000e+00,-2.320187e-01,-2.273603e-01
17,diag_bit_03,-5.930275e-02,1.599040e-03,-37.086462,4.643776e-301,-6.243681e-02,-5.616869e-02
18,diag_bit_04,-2.998277e-02,7.759969e-04,-38.637746,0.000000e+00,-3.150370e-02,-2.846184e-02
19,diag_bit_05,-3.513873e-02,1.748958e-03,-20.091236,8.804224e-90,-3.856662e-02,-3.171083e-02
20,diag_bit_06,1.097351e-02,1.776290e-02,0.617777,5.367224e-01,-2.384114e-02,4.578817e-02
21,diag_bit_07,-3.602928e-02,1.667554e-02,-2.160607,3.072574e-02,-6.871274e-02,-3.345824e-03
22,diag_bit_08,-8.265740e-04,2.445785e-02,-0.033796,9.730399e-01,-4.876307e-02,4.710992e-02
23,diag_bit_09,-4.618933e-02,2.777769e-02,-1.662821,9.634832e-02,-1.006326e-01,8.253953e-03
24,diag_bit_10,-2.885238e-02,1.836258e-03,-15.712596,1.239961e-55,-3.245138e-02,-2.525338e-02
25,diag_bit_11,-1.805935e-02,4.906488e-03,-3.680707,2.325881e-04,-2.767589e-02,-8.442805e-03
26,diag_bit_12,-2.707535e-02,7.683562e-03,-3.523802,4.254015e-04,-4.213486e-02,-1.201585e-02
27,diag_bit_13,-3.370084e-02,2.126648e-03,-15.846928,1.476241e-56,-3.786900e-02,-2.953269e-02
28,diag_bit_14,-1.047203e-02,2.344753e-03,-4.466154,7.963821e-06,-1.506766e-02,-5.876398e-03
29,diag_bit_15,-2.989719e-02,1.323620e-03,-22.587443,5.758518e-113,-3.249144e-02,-2.730294e-02

In [7]:
df_lett_re[COL_STATO_LETT].value_counts()
df_lett_re[COL_DIAGNOSTICA].value_counts()

NameError: name 'df_lett_re' is not defined